substitutions:
  _REGION: us-central1
  _REPOSITORY: is-it-down
  _TAG: latest
  _CACHE_TAG: latest

steps:
  - id: pull-checker-cache
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    entrypoint: bash
    args:
      - -c
      - >
        docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_CACHE_TAG}
        || exit 0

  - id: pull-api-cache
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    entrypoint: bash
    args:
      - -c
      - >
        docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_CACHE_TAG}
        || exit 0

  - id: pull-web-cache
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    entrypoint: bash
    args:
      - -c
      - >
        docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_CACHE_TAG}
        || exit 0

  - id: build-checker
    name: gcr.io/cloud-builders/docker
    waitFor: ["pull-checker-cache"]
    args:
      - build
      - -f
      - Dockerfile
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_CACHE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_CACHE_TAG}
      - .

  - id: build-api
    name: gcr.io/cloud-builders/docker
    waitFor: ["pull-api-cache"]
    args:
      - build
      - -f
      - Dockerfile.api
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_CACHE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_CACHE_TAG}
      - .

  - id: build-web
    name: gcr.io/cloud-builders/docker
    waitFor: ["pull-web-cache"]
    args:
      - build
      - -f
      - Dockerfile.web
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_CACHE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_CACHE_TAG}
      - .

  - id: push-checker
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-checker"]
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker

  - id: push-api
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-api"]
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api

  - id: push-web
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-web"]
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web

options:
  logging: CLOUD_LOGGING_ONLY
