substitutions:
  _REGION: us-central1
  _REPOSITORY: is-it-down
  _TAG: latest

steps:
  - id: build-checker
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_TAG}
      - .

  - id: build-api
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - -f
      - Dockerfile.api
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_TAG}
      - .

  - id: build-web
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - -f
      - Dockerfile.web
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_TAG}
      - .

  - id: push-checker
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-checker"]
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-checker:${_TAG}

  - id: push-api
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-api"]
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-api:${_TAG}

  - id: push-web
    name: gcr.io/cloud-builders/docker
    waitFor: ["build-web"]
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/is-it-down-web:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
